# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "deepstruct"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Simen Svale Skogsrud"]
  s.date = "2011-09-15"
  s.description = "A sibling of ostruct that handles deeply nested structures and basic data type detection"
  s.email = "simen@bengler.no"
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "README.markdown",
    "VERSION",
    "lib/deepstruct.rb"
  ]
  s.homepage = "http://github.com/simen/deepstruct"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "A sibling of ostruct that handles deeply nested structures and basic data type detection"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

